apiVersion: v1
kind: Service
metadata:
  name: lancache-dns
spec:
  type: LoadBalancer
  selector:
    app: lancache-dns
  ports:
    - name: dnstcp
      port: 53
      targetPort: dnstcp
      protocol: TCP
    - name: dnsudp
      port: 53
      targetPort: dnsudp
      protocol: UDP
  externalIPs:
    - "192.168.178.230"
