apiVersion: apps/v1
kind: Deployment
metadata:
  name: octoprint
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: octoprint
      app.kubernetes.io/name: octoprint
  replicas: 1
  securityContext:
    privileged: false
    runAsUser: 1000
    runAsGroup: 18 # dialout
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: octoprint
        app.kubernetes.io/name: octoprint
    spec:
      containers:
      - name: octoprint
        image: octoprint/octoprint:1.9.2
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /octoprint
          name: data
        - mountPath: /dev/ttyAnycubic
          name: printer
        env:
          - name: "ENABLE_MJPG_STREAMER"
            value: "false"
          - name: "TZ"
            value: "Europe/Berlin"
          - name: "OCTOPRINT_PORT"
            value: "80"
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: octoprint
      - name: printer
        hostPath:
          path: /dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0
          type: CharDevice
