apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: main
spec:
  addresses:
    - 192.168.178.226-192.168.178.254
  autoAssign: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: main
spec:
  ipAddressPools:
  - main