image:
  repository: docker.io/homeassistant/home-assistant
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: false

persistence:
  enabled: yes
  storage: 2G
  volumeName: pvc-f2e7bbc9-49e2-43a4-8ea0-4c52caa164de

resources:
  limits:
    squat.ai/skyconnect: 1

nodeSelector: {}

tolerations: []

affinity: {}
