image:
  repository: docker.io/homeassistant/home-assistant
  pullPolicy: IfNotPresent
  tag: ""

skyconnect:
  hostPath: /dev/serial/by-id/usb-Nabu_Casa_SkyConnect_v1.0_265d5ba51d97ed1197e3c998a7669f5d-if00-port0

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext:
  privileged: true

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: false

persistence:
  enabled: yes
  storage: 2G
  volumeName: pvc-f2e7bbc9-49e2-43a4-8ea0-4c52caa164de

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
