apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "homeassistant.fullname" . }}-extra-init
  labels:
    {{- include "homeassistant.labels" . | nindent 4 }}
data:
  00-ln-serial: |-
    #!/usr/bin/with-contenv bash
    id=0
    
    for port in /dev/serial/by-id/*; do
      ln -vs "$port" /dev/ttyUSB$id
      ((id++))
    done

    exit 0
