{{- if .Values.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "homeassistant.fullname" . }}
  labels:
    {{- include "homeassistant.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.persistence.storage | default "1G" }}"
  {{- if .Values.persistence.volumeName -}}
  volumeName: "{{ .Values.persistence.volumeName }}"
  {{- end }}
{{- end }}
