apiVersion: apps/v1
kind: Deployment
metadata:
  name: ebon-bot
spec:
  selector:
    matchLabels:
      app: ebon-bot
  template:
    metadata:
      labels:
        app: ebon-bot
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: ebons
      containers:
      - name: ebb
        image: ghcr.io/webd97/ebon-bot:sha-6e28365
        volumeMounts:
          - name: data
            mountPath: /mnt/ebons
        env:
        - name: EBB_IMAP_HOST
          valueFrom:
            secretKeyRef:
              name: ebon-bot
              key: imap-host
        - name: EBB_IMAP_USERNAME
          valueFrom:
            secretKeyRef:
              name: ebon-bot
              key: imap-username
        - name: EBB_IMAP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ebon-bot
              key: imap-password
        - name: EBB_IMAP_PORT
          valueFrom:
            secretKeyRef:
              name: ebon-bot
              key: imap-port
        - name: EBB_IMAP_BOX
          valueFrom:
            secretKeyRef:
              name: ebon-bot
              key: imap-inbox
        - name: EBB_SAVE_DIRECTORY
          value: /mnt/ebons
        - name: EBB_TELEGRAM_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: ebon-bot
              key: telegram-token
        - name: EBB_TELEGRAM_API_ID
          valueFrom:
            secretKeyRef:
              name: ebon-bot
              key: telegram-api-id
        - name: EBB_TELEGRAM_API_HASH
          valueFrom:
            secretKeyRef:
              name: ebon-bot
              key: telegram-api-hash
        - name: EBB_TELEGRAM_PEER
          valueFrom:
            secretKeyRef:
              name: ebon-bot
              key: telegram-username
