apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
data:
  Corefile: |-
    .:53 {
        errors
        health {
            lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
            pods insecure
            fallthrough in-addr.arpa ip6.arpa
            ttl 30
        }
        k8s_external k8s.home
        forward . 192.168.39.3
        cache 30
        loop
        reload
        loadbalance
    }
