paperless-ngx:
  env:
    TZ: Europe/Berlin
  
  service:
    main:
      type: LoadBalancer
  
  persistence:
    data:
      enabled: true
      accessMode: ReadWriteOnce
      size: 5Gi
    media:
      enabled: true
      accessMode: ReadWriteOnce
      size: 5Gi
    export:
      enabled: true
      accessMode: ReadWriteOnce
      size: 1Gi
    consume:
      enabled: true
      accessMode: ReadWriteOnce
      size: 1Gi

  postgresql:
    enabled: true
    auth:
      database: paperless
      existingSecret: paperless-pg
    primary:
      persistence:
        enabled: true
        size: 8Gi

  redis:
    enabled: true
    auth:
      enabled: true
    master:
      persistence:
        enabled: true
        size: 8Gi
