paperless-ngx:
  env:
    TZ: Europe/Berlin
  
  service:
    type: LoadBalancer

postgresql:
  enabled: true
  auth:
    database: paperless
    existingSecret: paperless-pg
  primary:
    persistence:
      enabled: true
      size: 8Gi

redis:
  enabled: true
  auth:
    enabled: true
  master:
    persistence:
      enabled: true
      size: 8Gi
