apiVersion: v1
kind: Service
metadata:
  name: lancache-monolithic
spec:
  type: LoadBalancer
  selector:
    app: lancache-monolithic
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: https
      port: 443
      targetPort: https
  loadBalancerIP: 192.168.178.227
